Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/storage/homefs/ns12l060/mialab/mia_experiments/__init__.py", line 9, in <module>
    from .core.data import ExperimentData, DataLoader, ExperimentCollection
  File "/storage/homefs/ns12l060/mialab/mia_experiments/core/__init__.py", line 3, in <module>
    from .data import ExperimentData, DataLoader, ExperimentCollection
  File "/storage/homefs/ns12l060/mialab/mia_experiments/core/data.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
